spring.application.name=b2b-backend
server.port=8090

# Configuracion Base de Datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/suitchase?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# Logging
logging.level.com.tasf.b2b=INFO
